### ISSUE TITLE
suggestions for gwas.py

### ISSUE THREAD

**Issue by joellepasman** [comorment/containers#6] opened 2021-06-30 12:46 UTC
- Perhaps add effect allele frequency in the outputted sumstats?
- The regenie jobs created with the argsfile contain an extra --bt argument that I think can be removed
- The sbatch commands do not work on our system, on Bianca you need to specify -A (account/ project for computational time) and -p (node / core with -n)
- The 'parallel' command in gwas_real is not recognized, here it's a module that needs to be loaded first (whereas signularity on the other hand is not a module)
- Does regenie have flags for some standard QC, like MAF, missingness, or HWE filtering? Maybe some of these standard QC checks could be built in
- Would it be an idea to auto-generate a readme for the output? Just so you can see in one glance which was the reference allele, on which scale are the BETA and SE, etc.

**Comment by ofrei** [comment] 2021-06-30 12:48
:+1: very good points, I'll look into these

**Comment by joellepasman** [comment] 2021-07-05 09:21
I have more!

- Maybe create some flexibility for reading pheno and covar files, e.g. reading phenotypes from a .fam file; reading covariates from a different file than the phenotype file; using a different field separator (or maybe be a bit more explicit about such requirements)
- I'd like to be able to use the --c12 option from regenie
- In all regenie jobs I have run so far I get this error message: `ERROR: One of the folds has only cases/controls! Either use smaller #folds (option --cv) or use LOOCV (option --loocv)` Perhaps specify the -loocv option by default?
- Could you built in a function to deal with chromosome codes other than 1-22?

**Comment by joellepasman** [comment] 2021-07-06 09:05
And another important one: it appears that regenie cannot deal with vcf files for the first step? You offer the arguments bed-fit or bgen-fit, but no vcf-fit? For now I convert the vcf files to bgen with plink, but I'm not certain I won't loose any dosage (certainty) information (see https://www.cog-genomics.org/plink/2.0/data#export). What are your thoughts on this?

**Comment by ofrei** [comment] 2021-07-06 11:03
@joellepasman thanks for extra comments - will look into it / try to implement as soon as I have time.

from what I see in https://rgcgithub.github.io/regenie/options/#genetic-data-file-format regenie doesn't support vcf. I don't know how good is plink2 at convertig vcf to bgen. I would consider using the qctool2 ( https://www.well.ox.ac.uk/~gav/qctool_v2/documentation/examples/converting.html  ), but it might be substantially slower than plink2. I would convert a small fraction of the plink-generated .bgen back into .vcf to see if you still see dosages - and if that's the case than your current plink procedure is good, right?

**Comment by joellepasman** [comment] 2021-07-06 11:07
Ah those are excellent suggestions, thanks, I will keep you posted how it works out.

**Comment by joellepasman** [comment] 2021-08-11 14:38
I have a fresh suggestion: could gwas.py allow for specification of genotype files splitted up per chromosome?

**Comment by ofrei** [comment] 2021-08-17 21:54
I've made some changes that address what's marked as [fixed] .. 
[TBD] is on my ToDo list of things to solve ASAP. 
[postponed] require a larger development - this is something we should do, but perhaps after discussing further details.
[won't fix] is what IMHO should work as it is today (see a comment why, but i'm open to discuss)

* [fixed] The regenie jobs created with the argsfile contain an extra --bt argument that I think can be removed
* [fixed] Support for .vcf files (note that PLINK is picky about sample IDs in .vcf files)
* [fixed] Genotype split per chromosome
* [fixed] Perhaps add effect allele frequency in the outputted sumstats [A1_FREQ]
* [fixed] ERROR: One of the folds has only cases/controls - added "--loocv" by default
* [fixed] 95 CI
* [fixed] add CaseN and ControlN columns
* [fixed what's relevant to rename, other cols documented] * update sumstats columns, rename
* [TBD] auto-generate README output
* [postponed] -a / -p require a larger effort to make Nextflow scripts
* [postponed] flexibility in reading .pheno / .dict files
* [postponed] support for non-autosomes
* [postponed] implement standard QC filters (MAF & INFO) - not fixed for now, we need a way of loading INFO scores into gwas.py.
* [won't fix] --c12 option for regenie - not available by design. The phenotype file must be formatted according to the spec, which says "Binary variables must be encoded as 1 (cases) and 0 (controls).". gwas.py automatically converts this to the format expected by the plink / regenie software. Can be implemented later to make phenotype format more flexible, if needed.

**Comment by ofrei** [comment] 2021-08-18 11:00
@joellepasman I'v addressed most of the suggestions. Could you create three separate tickets for the remaining improvements:
[postponed] -a / -p require a larger effort to make Nextflow scripts
[postponed] flexibility in reading .pheno / .dict files (the --c12 option is part of this flexibility, please mention it here)
[postponed] support for non-autosomes
Thanks!

**Closed** 2021-08-18 12:51 UTC
